name: deploy-hexo-blog
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # 确保子模块被检出
      # 更新子模块
      - name: Update submodules
        run: |
          git submodule init
          git submodule update

      # 安装nodejs
      - name: install nodejs
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "20.12.0"
      # 使用pnpm包管理
      - name: use pnpm
        run: npm i -g pnpm && pnpm config set registry https://registry.npmmirror.com
      # 安装依赖
      - name: install packages
        run: pnpm install --no-frozen-lockfile
      # 清空缓存
      - name: clear
        run: pnpm run clean
      # 打包项目
      - name: build
        run: pnpm run build
      # 部署项目
      - name: deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "public/"
          target: ${{ secrets.REMOTE_TARGET }}
      # 推送博客链接
      - name: Clean up unnecessary files
        run: |
          mkdir -p temp
          mv .github temp/
          mv public/baidu.txt temp/
          mv public/bing.json temp/
          mv public/google.txt temp/        
      - name: push links
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }} # 填写ssh私钥
          exclude_assets: "" # 排除.github目录
          external_repository: codepzj/blog-auto-push
          publish_branch: main
          publish_dir: ./temp
          commit_message: ${{ github.event.head_commit.message }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
      
